In [1]:
import numpy as np
print("******TYPE OF ARRAYS*******")
a = np.array([[1, 2, 3],[4,5,6]])
b=np.zeros(3)  
c=np.ones((2,3))    
d=np.arange(0,10,2) 
print(f"One dimension array :{a}\n Zero array :{b}\n One Array:{c}\n Ranged array:{d}\n")


******TYPE OF ARRAYS*******
One dimension array :[[1 2 3]
 [4 5 6]]
 Zero array :[0. 0. 0.]
 One Array:[[1. 1. 1.]
 [1. 1. 1.]]
 Ranged array:[0 2 4 6 8]



In [2]:
#array shape
print("*****OPERATION ON ARRAYS*****")
print(a.shape)
#dimension
print(a.ndim)
#size
print(a.size)
#dtype
print(a.dtype)


*****OPERATION ON ARRAYS*****
(2, 3)
2
6
int64


In [3]:
#INDEXING
print("***INDEXING***")
print(a[0])
print(a[-1])
print(a[1:4])

***INDEXING***
[1 2 3]
[4 5 6]
[[4 5 6]]


In [6]:
#***MATHS FUNCTIONS **

print("**MATHS FUNCTION**")
print(np.sqrt(a))      
print(np.mean(a))      
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.std(a))

**MATHS FUNCTION**
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
3.5
21
6
1
1.707825127659933


In [7]:
#************PADNDAS LIBRARY*****
import pandas as pd
data = {"Name": ["A", "B", "C"],"Marks": [80, 90, 85]}
df = pd.DataFrame(data)
print(df)


  Name  Marks
0    A     80
1    B     90
2    C     85


In [8]:
print("***BASIC OPERATION***")
print(df.head())
print(df.tail())
print(df.shape)
print(df.info())
print(df.describe())

print("**INDEXING***\n")
print(df.loc[0])
print(df.iloc[0])

***BASIC OPERATION***
  Name  Marks
0    A     80
1    B     90
2    C     85
  Name  Marks
0    A     80
1    B     90
2    C     85
(3, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Marks   3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes
None
       Marks
count    3.0
mean    85.0
std      5.0
min     80.0
25%     82.5
50%     85.0
75%     87.5
max     90.0
**INDEXING***

Name      A
Marks    80
Name: 0, dtype: object
Name      A
Marks    80
Name: 0, dtype: object


In [9]:
print("**Filtering data**\n")
print(df[df["Marks"]>85])

print(df.drop_duplicates())
print(df.isnull())
print(df.isnull().sum())
print(df.fillna(0,inplace=True))


**Filtering data**

  Name  Marks
1    B     90
  Name  Marks
0    A     80
1    B     90
2    C     85
    Name  Marks
0  False  False
1  False  False
2  False  False
Name     0
Marks    0
dtype: int64
None
